### ISSUE TITLE
pip installation fails 

### ISSUE THREAD

**Issue by mturilli** [Francis-Liu/aimes.bundle#4]
The aimes.bundle module cannot be installed from pypi because it fails with the following:

```
$ pip install aimes.bundle
Downloading/unpacking aimes.bundle
  Downloading aimes.bundle-0.0.2.tar.gz (454kB): 454kB downloaded
...
error: can't copy 'etc/aimes_bundle_bandwidth.cfg': doesn't exist or not a regular file
```

**Comment by Francis-Liu** [comment]
I fixed it and it works on my computer. Pls give it another try.

**Comment by mturilli** [comment]
Thank you. Tested and now it works. Would you mind to push it to pypi?

**Comment by Francis-Liu** [comment]
I already did. Actually, I have used pypi to test it.

**Comment by mturilli** [comment]
Thank you!
